// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Vetly.Infrastructure.Data;

#nullable disable

namespace Vetly.Infrastructure.Migrations
{
    [DbContext(typeof(VetlyDbContext))]
    [Migration("20260805090703_Fase04_MaquinaEstadosConsulta")]
    partial class Fase04_MaquinaEstadosConsulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vetly.Domain.Entities.Animal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("ALERGIAS");

                    b.Property<string>("AlertasAtivos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("ALERTAS_ATIVOS");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CarteiraVacinacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("CARTEIRA_VACINACAO");

                    b.Property<bool>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<string>("CondicoesPreExistentes")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("CONDICOES_PREEXISTENTES");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("FOTO_URL");

                    b.Property<string>("MedicacoesEmUso")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("MEDICACOES_EM_USO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("RACA");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.Property<int>("Sexo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SEXO");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_ANIMAL_RESPONSAVEL");

                    b.ToTable("TB_ANIMAL", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.ConsentimentoLgpd", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Concedido")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONCEDIDO");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO");

                    b.Property<DateTime?>("DataRevogacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO");

                    b.Property<int>("Finalidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FINALIDADE");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId", "Finalidade")
                        .HasDatabaseName("IX_CONSENTIMENTO_RESPONSAVEL_FINALIDADE");

                    b.ToTable("TB_CONSENTIMENTO_LGPD", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Consulta", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<short>("ContadorRemarcacoes")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("CONTADOR_REMARCACOES");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<DateTime?>("DataRealizada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REALIZADA");

                    b.Property<bool>("DiagnosticoValidado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DIAGNOSTICO_VALIDADO");

                    b.Property<DateTime?>("LockCheckoutExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LOCK_CHECKOUT_EXPIRA_EM");

                    b.Property<int>("Modalidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODALIDADE");

                    b.Property<string>("PreSintomas")
                        .HasMaxLength(4000)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("PRE_SINTOMAS");

                    b.Property<bool>("ProtocoloValidado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PROTOCOLO_VALIDADO");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("TipoServico")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_SERVICO");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_CONSULTA_ANIMAL");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("IX_CONSULTA_DATA");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_CONSULTA_VETERINARIO");

                    b.ToTable("TB_CONSULTA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Documento", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AssinadoDigitalmente")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ASSINADO_DIGITALMENTE");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("CrmvSignatario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SIGNATARIO");

                    b.Property<string>("CrmvSolicitanteCorrecao")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SOLICITANTE_CORRECAO");

                    b.Property<DateTime?>("DataCorrecao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CORRECAO");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_GERACAO");

                    b.Property<string>("InternacaoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("INTERNACAO_ID");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_DOCUMENTO");

                    b.Property<int>("Versao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSAO");

                    b.Property<string>("VersaoOriginalId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VERSAO_ORIGINAL_ID");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_DOCUMENTO_CONSULTA");

                    b.HasIndex("InternacaoId")
                        .HasDatabaseName("IX_DOCUMENTO_INTERNACAO");

                    b.ToTable("TB_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AdministradorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ADMINISTRADOR_ID");

                    b.Property<bool>("Ativa")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("NOME");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .HasDatabaseName("IX_EMPRESA_ADMINISTRADOR");

                    b.ToTable("TB_EMPRESA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Exame", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime?>("DataResultado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RESULTADO");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SOLICITACAO");

                    b.Property<bool>("LiberadoAoResponsavel")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LIBERADO_AO_RESPONSAVEL");

                    b.Property<string>("Resultado")
                        .HasColumnType("CLOB")
                        .HasColumnName("RESULTADO");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("TIPO_SOLICITACAO");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_EXAME_ANIMAL");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_EXAME_VETERINARIO");

                    b.ToTable("TB_EXAME", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Internacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ABERTURA");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALTA");

                    b.Property<string>("ProcedimentosDiarios")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("PROCEDIMENTOS_DIARIOS");

                    b.Property<decimal>("ValorCaucao")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_CAUCAO");

                    b.Property<decimal>("ValorTotalApurado")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_TOTAL_APURADO");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_INTERNACAO_ANIMAL");

                    b.ToTable("TB_INTERNACAO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.LembreteAgendado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AlertaEnviadoClinica")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ALERTA_ENVIADO_CLINICA");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EVENTO");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.Property<bool>("ResponsavelRespondeu")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("RESPONSAVEL_RESPONDEU");

                    b.Property<int>("TentativasRealizadas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TENTATIVAS_REALIZADAS");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_LEMBRETE_ANIMAL");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_LEMBRETE_RESPONSAVEL");

                    b.ToTable("TB_LEMBRETE", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Pagamento", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("InternacaoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("INTERNACAO_ID");

                    b.Property<int>("MeioPagamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEIO_PAGAMENTO");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MOMENTO");

                    b.Property<decimal>("PercentualSplit")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_SPLIT");

                    b.Property<string>("ResponsavelId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RESPONSAVEL_ID");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS_PAGAMENTO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR");

                    b.Property<decimal?>("ValorEstornado")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_ESTORNADO");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_PAGAMENTO_CONSULTA");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("IX_PAGAMENTO_RESPONSAVEL");

                    b.ToTable("TB_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Prontuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AlertaSeguranca")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ALERTA_SEGURANCA");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("CrmvSolicitanteCorrecao")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SOLICITANTE_CORRECAO");

                    b.Property<string>("DadosClinicos")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("DADOS_CLINICOS");

                    b.Property<DateTime?>("DataCorrecao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CORRECAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("JustificativaCorrecao")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("JUSTIFICATIVA_CORRECAO");

                    b.Property<string>("VersaoOriginalId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VERSAO_ORIGINAL_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_PRONTUARIO_ANIMAL");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_PRONTUARIO_CONSULTA");

                    b.ToTable("TB_PRONTUARIO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.RegistroOcultado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("DataOcultacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_OCULTACAO");

                    b.Property<string>("ProntuarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("PRONTUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "ProntuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_REGISTRO_OCULTADO_ANIMAL_PRONTUARIO");

                    b.ToTable("TB_REGISTRO_OCULTADO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Responsavel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime?>("BloqueadoDescontosAte")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BLOQUEADO_DESCONTOS_ATE");

                    b.Property<byte>("ContadorNoShows")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("CONTADOR_NO_SHOWS");

                    b.Property<DateTime?>("DataUltimoNoShow")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ULTIMO_NO_SHOW");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("VARCHAR2(254)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("SaldoCreditosVetly")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("SALDO_CREDITOS_VETLY");

                    b.Property<int>("SaldoPontos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SALDO_PONTOS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.Property<int>("TierFidelidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIER_FIDELIDADE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_RESPONSAVEL_EMAIL");

                    b.ToTable("TB_RESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Veterinario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("ESPECIALIDADES");

                    b.Property<string>("EspeciesAtendidas")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("ESPECIES_ATENDIDAS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<int>("Persona")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONA");

                    b.Property<int>("Plano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANO");

                    b.Property<string>("TitulacaoAcademica")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("TITULACAO_ACADEMICA");

                    b.Property<string>("UfAtuacao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("UF_ATUACAO");

                    b.HasKey("Id");

                    b.HasIndex("UfAtuacao")
                        .HasDatabaseName("IX_VETERINARIO_UF");

                    b.ToTable("TB_VETERINARIO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Veterinario", b =>
                {
                    b.OwnsOne("Vetly.Domain.ValueObjects.Crmv", "Crmv", b1 =>
                        {
                            b1.Property<string>("VeterinarioId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(15)")
                                .HasColumnName("CRMV");

                            b1.HasKey("VeterinarioId");

                            b1.ToTable("TB_VETERINARIO");

                            b1.WithOwner()
                                .HasForeignKey("VeterinarioId");
                        });

                    b.Navigation("Crmv")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
