// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Vetly.Infrastructure.Data;

#nullable disable

namespace Vetly.Infrastructure.Migrations
{
    [DbContext(typeof(VetlyDbContext))]
    [Migration("20260831183455_CorrigeFidelidadeParaRegrasFechadas")]
    partial class CorrigeFidelidadeParaRegrasFechadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vetly.Domain.Entities.AcessoColmeia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("ConcedidoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONCEDIDO_EM");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<int>("Escopo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESCOPO");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("MOTIVO");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REVOGADO_EM");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("IX_ACESSO_COLMEIA_EXPIRA_EM");

                    b.HasIndex("AnimalId", "VeterinarioId")
                        .HasDatabaseName("IX_ACESSO_COLMEIA_ANIMAL_VET");

                    b.ToTable("TB_ACESSO_COLMEIA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.AgendaConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ATUALIZADA_EM");

                    b.Property<int>("Dias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DIAS");

                    b.Property<byte>("DuracaoMinutos")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("DURACAO_MINUTOS");

                    b.Property<byte>("FimEmMinutos")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("FIM_EM_MINUTOS");

                    b.Property<byte>("InicioEmMinutos")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("INICIO_EM_MINUTOS");

                    b.Property<byte>("IntervaloMinutos")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("INTERVALO_MINUTOS");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_AGENDA_CONFIG_VETERINARIO");

                    b.ToTable("TB_AGENDA_CONFIG", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Animal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("ALERGIAS");

                    b.Property<string>("AlertasAtivos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("ALERTAS_ATIVOS");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CarteiraVacinacao")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CARTEIRA_VACINACAO");

                    b.Property<bool?>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<string>("CondicoesPreexistentes")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("CONDICOES_PREEXISTENTES");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("FotoMidiaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("FOTO_MIDIA_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("RACA");

                    b.Property<int?>("Sexo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SEXO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("IX_ANIMAL_TUTOR");

                    b.ToTable("TB_ANIMAL", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("COMENTARIO");

                    b.Property<bool>("ComentarioModerado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("COMENTARIO_MODERADO");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("MotivoDaModeracao")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("MOTIVO_MODERACAO");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("NOTA");

                    b.Property<DateTime?>("RespondidaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RESPONDIDA_EM");

                    b.Property<string>("RespostaDoVeterinario")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("RESPOSTA_VETERINARIO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique()
                        .HasDatabaseName("IX_AVALIACAO_CONSULTA");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_AVALIACAO_VETERINARIO");

                    b.ToTable("TB_AVALIACAO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.CepCoordenada", b =>
                {
                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("CIDADE");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("UF");

                    b.HasKey("Cep");

                    b.HasIndex("Cidade", "Uf")
                        .HasDatabaseName("IX_CEP_COORDENADA_CIDADE");

                    b.ToTable("TB_CEP_COORDENADA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Consulta", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<bool>("Cancelada")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CANCELADA");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<bool>("DiagnosticoValidado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DIAGNOSTICO_VALIDADO");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ENCERRADA_EM");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FINALIZADA");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIADA_EM");

                    b.Property<int>("Modalidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODALIDADE");

                    b.Property<int>("Origem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORIGEM");

                    b.Property<bool>("ProtocoloValidado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PROTOCOLO_VALIDADO");

                    b.Property<string>("ServicoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SERVICO_ID");

                    b.Property<string>("SlotId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SLOT_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS_PAGAMENTO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_CONSULTA_ANIMAL");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("IX_CONSULTA_DATA");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CONSULTA_STATUS");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_CONSULTA_VETERINARIO");

                    b.ToTable("TB_CONSULTA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.CupomResgate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<int>("Categoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ITEM_CATEGORIA");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("CODIGO_QR");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DESCONTO");

                    b.Property<decimal>("DescontoPrestador")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DESCONTO_PRESTADOR");

                    b.Property<decimal>("DescontoVetly")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DESCONTO_VETLY");

                    b.Property<DateTime>("EmitidoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EMITIDO_EM");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<int>("Faixa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FAIXA");

                    b.Property<string>("ItemNome")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("ITEM_NOME");

                    b.Property<string>("ItemRef")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("ITEM_REF");

                    b.Property<int>("PontosDebitados")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTOS_DEBITADOS");

                    b.Property<DateTime?>("ResgatadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RESGATADO_EM");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("CodigoQr")
                        .IsUnique()
                        .HasDatabaseName("IX_CUPOM_CODIGO");

                    b.HasIndex("Status", "ExpiraEm")
                        .HasDatabaseName("IX_CUPOM_STATUS_EXPIRA");

                    b.HasIndex("TutorId", "EmitidoEm")
                        .HasDatabaseName("IX_CUPOM_TUTOR");

                    b.ToTable("TB_CUPOM_RESGATE", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int>("Plataforma")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLATAFORMA");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PUSH_TOKEN");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTRADO_EM");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<DateTime>("UltimoUsoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_USO_EM");

                    b.HasKey("Id");

                    b.HasIndex("PushToken")
                        .IsUnique()
                        .HasDatabaseName("IX_DISPOSITIVO_PUSH_TOKEN");

                    b.HasIndex("TutorId", "Ativo")
                        .HasDatabaseName("IX_DISPOSITIVO_TUTOR");

                    b.ToTable("TB_DISPOSITIVO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Documento", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AssinadoDigitalmente")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ASSINADO_DIGITALMENTE");

                    b.Property<string>("AssinaturaCarimbo")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("ASSINATURA_CARIMBO");

                    b.Property<string>("AssinaturaMetodo")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ASSINATURA_METODO");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("Conteudo")
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTEUDO");

                    b.Property<string>("CrmvSignatario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SIGNATARIO");

                    b.Property<string>("CrmvSolicitanteCorrecao")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SOLICITANTE_CORRECAO");

                    b.Property<DateTime?>("DataCorrecao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CORRECAO");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_GERACAO");

                    b.Property<string>("InternacaoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("INTERNACAO_ID");

                    b.Property<DateTime?>("LidoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LIDO_EM");

                    b.Property<string>("PdfMidiaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("PDF_MIDIA_ID");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PUBLICADO_EM");

                    b.Property<int?>("Subtipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUBTIPO");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_DOCUMENTO");

                    b.Property<int>("Versao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSAO");

                    b.Property<string>("VersaoOriginalId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VERSAO_ORIGINAL_ID");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_DOCUMENTO_CONSULTA");

                    b.HasIndex("InternacaoId")
                        .HasDatabaseName("IX_DOCUMENTO_INTERNACAO");

                    b.ToTable("TB_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AdministradorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ADMINISTRADOR_ID");

                    b.Property<bool>("Ativa")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVA");

                    b.Property<int?>("FaixaEnterprise")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FAIXA_ENTERPRISE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("PercentualRetencaoParcial")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_RETENCAO_PARCIAL");

                    b.Property<int>("Plano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .HasDatabaseName("IX_EMPRESA_ADMINISTRADOR");

                    b.ToTable("TB_EMPRESA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Exame", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime?>("DataResultado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RESULTADO");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_SOLICITACAO");

                    b.Property<bool>("LiberadoAoTutor")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LIBERADO_AO_TUTOR");

                    b.Property<string>("Resultado")
                        .HasColumnType("CLOB")
                        .HasColumnName("RESULTADO");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("TIPO_SOLICITACAO");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_EXAME_ANIMAL");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_EXAME_VETERINARIO");

                    b.ToTable("TB_EXAME", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Internacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ABERTURA");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALTA");

                    b.Property<string>("ProcedimentosDiarios")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("PROCEDIMENTOS_DIARIOS");

                    b.Property<decimal>("ValorCaucao")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_CAUCAO");

                    b.Property<decimal>("ValorTotalApurado")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_TOTAL_APURADO");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_INTERNACAO_ANIMAL");

                    b.ToTable("TB_INTERNACAO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.ItemListaEspera", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<int>("Necessidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NECESSIDADE");

                    b.Property<DateTime?>("PrioridadeAte")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PRIORIDADE_ATE");

                    b.Property<string>("SlotOferecidoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SLOT_OFERECIDO_ID");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("IX_LISTA_ESPERA_TUTOR");

                    b.HasIndex("VeterinarioId", "Estado", "CriadoEm")
                        .HasDatabaseName("IX_LISTA_ESPERA_FILA");

                    b.ToTable("TB_LISTA_ESPERA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Job", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONCLUIDO_EM");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("ExecutarEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXECUTAR_EM");

                    b.Property<string>("Payload")
                        .HasMaxLength(2000)
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("PAYLOAD");

                    b.Property<byte>("Tentativas")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("TENTATIVAS");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("ULTIMO_ERRO");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "ExecutarEm")
                        .HasDatabaseName("IX_JOB_FILA");

                    b.ToTable("TB_JOB", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.LembreteAgendado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AlertaEnviadoClinica")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ALERTA_ENVIADO_CLINICA");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EVENTO");

                    b.Property<int>("TentativasRealizadas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TENTATIVAS_REALIZADAS");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<bool>("TutorRespondeu")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("TUTOR_RESPONDEU");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_LEMBRETE_ANIMAL");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("IX_LEMBRETE_TUTOR");

                    b.ToTable("TB_LEMBRETE", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.LogAcessoColmeia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AcessoColmeiaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ACESSO_COLMEIA_ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<int>("Escopo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESCOPO");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OCORRIDO_EM");

                    b.Property<bool>("Permitido")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PERMITIDO");

                    b.Property<string>("Rota")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("ROTA");

                    b.Property<string>("VeterinarioId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("IX_LOG_COLMEIA_VETERINARIO");

                    b.HasIndex("AnimalId", "OcorridoEm")
                        .HasDatabaseName("IX_LOG_COLMEIA_ANIMAL_OCORRIDO");

                    b.ToTable("TB_LOG_ACESSO_COLMEIA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.LogAuditoriaIa", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AlterouSugestao")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ALTEROU_SUGESTAO");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("ConteudoFinal")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTEUDO_FINAL");

                    b.Property<int>("Decisao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DECISAO");

                    b.Property<string>("Justificativa")
                        .HasColumnType("CLOB")
                        .HasColumnName("JUSTIFICATIVA");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("MODELO");

                    b.Property<string>("RascunhoIaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("RASCUNHO_IA_ID");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTRADO_EM");

                    b.Property<string>("SessaoCapturaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SESSAO_CAPTURA_ID");

                    b.Property<string>("VeterinarioId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_AUDITORIA_IA_CONSULTA");

                    b.HasIndex("RegistradoEm")
                        .HasDatabaseName("IX_AUDITORIA_IA_REGISTRADO_EM");

                    b.ToTable("TB_LOG_AUDITORIA_IA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Midia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("ChaveStorage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("CHAVE_STORAGE");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADA_EM");

                    b.Property<DateTime?>("RetencaoAte")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RETENCAO_ATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TAMANHO_BYTES");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("TutorId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("ChaveStorage")
                        .IsUnique()
                        .HasDatabaseName("IX_MIDIA_CHAVE");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_MIDIA_CONSULTA");

                    b.HasIndex("Status", "RetencaoAte")
                        .HasDatabaseName("IX_MIDIA_RETENCAO");

                    b.ToTable("TB_MIDIA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.MovimentoDePontos", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("CupomId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CUPOM_ID");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<string>("MovimentoOrigemId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("MOVIMENTO_ORIGEM_ID");

                    b.Property<decimal>("Multiplicador")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("MULTIPLICADOR");

                    b.Property<string>("ObrigacaoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("OBRIGACAO_ID");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OCORRIDO_EM");

                    b.Property<string>("PagamentoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("PAGAMENTO_ID");

                    b.Property<int>("Pontos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTOS");

                    b.Property<int>("PontosBrutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTOS_BRUTOS");

                    b.Property<int>("Restante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESTANTE");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<decimal?>("ValorEmReais")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_EM_REAIS");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_PONTOS_CONSULTA");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("IX_PONTOS_EXPIRA_EM");

                    b.HasIndex("ObrigacaoId")
                        .HasDatabaseName("IX_PONTOS_OBRIGACAO");

                    b.HasIndex("TutorId", "OcorridoEm")
                        .HasDatabaseName("IX_PONTOS_TUTOR_OCORRIDO");

                    b.ToTable("TB_MOVIMENTO_PONTOS", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Notificacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("AgendadaPara")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AGENDADA_PARA");

                    b.Property<string>("AnimalId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("CORPO");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESTINO");

                    b.Property<DateTime?>("EnviadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ENVIADA_EM");

                    b.Property<DateTime?>("LidaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LIDA_EM");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<byte>("Tentativas")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("TENTATIVAS");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("TITULO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("ULTIMO_ERRO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "Tipo")
                        .HasDatabaseName("IX_NOTIFICACAO_ANIMAL_TIPO");

                    b.HasIndex("Status", "AgendadaPara")
                        .HasDatabaseName("IX_NOTIFICACAO_STATUS_AGENDADA");

                    b.HasIndex("TutorId", "CriadaEm")
                        .HasDatabaseName("IX_NOTIFICACAO_TUTOR_CRIADA");

                    b.ToTable("TB_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.ObrigacaoPet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<bool>("Arquivada")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ARQUIVADA");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADA_EM");

                    b.Property<bool>("DerivadaDaCarteira")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DERIVADA_CARTEIRA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("DESCRICAO");

                    b.Property<short>("PeriodicidadeEmDias")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("PERIODICIDADE_DIAS");

                    b.Property<DateTime>("ProximoVencimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PROXIMO_VENCIMENTO");

                    b.Property<string>("RegistradaPorVeterinarioId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("REGISTRADA_POR_VET_ID");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<string>("UltimaConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ULTIMA_CONSULTA_ID");

                    b.Property<DateTime?>("UltimoCumprimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_CUMPRIMENTO");

                    b.HasKey("Id");

                    b.HasIndex("ProximoVencimento")
                        .HasDatabaseName("IX_OBRIGACAO_VENCIMENTO");

                    b.HasIndex("AnimalId", "Arquivada")
                        .HasDatabaseName("IX_OBRIGACAO_ANIMAL");

                    b.ToTable("TB_OBRIGACAO_PET", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Pagamento", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("ChaveIdempotencia")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CHAVE_IDEMPOTENCIA");

                    b.Property<decimal?>("Comissao")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("COMISSAO");

                    b.Property<string>("ConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("CupomId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CUPOM_ID");

                    b.Property<decimal?>("DescontoPrestador")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DESCONTO_PRESTADOR");

                    b.Property<decimal?>("DescontoVetly")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("DESCONTO_VETLY");

                    b.Property<string>("DestinatarioRepasseId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("DESTINATARIO_REPASSE_ID");

                    b.Property<int?>("FaixaDoDesconto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FAIXA_DESCONTO");

                    b.Property<string>("InternacaoId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("INTERNACAO_ID");

                    b.Property<bool>("Liquidado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LIQUIDADO");

                    b.Property<int>("MeioPagamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEIO_PAGAMENTO");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MOMENTO");

                    b.Property<decimal>("PercentualSplit")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_SPLIT");

                    b.Property<int?>("PlanoAplicado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANO");

                    b.Property<int?>("PontosResgatados")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PONTOS_RESGATADOS");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("REFERENCIA_EXTERNA");

                    b.Property<decimal?>("Repasse")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("REPASSE");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS_PAGAMENTO");

                    b.Property<decimal?>("TakeRate")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TAKE_RATE");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("TUTOR_ID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR");

                    b.Property<decimal?>("ValorDoDesconto")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_DO_DESCONTO");

                    b.Property<decimal?>("ValorEstornado")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR_ESTORNADO");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_PAGAMENTO_CONSULTA");

                    b.HasIndex("ReferenciaExterna")
                        .HasDatabaseName("IX_PAGAMENTO_REFERENCIA");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("IX_PAGAMENTO_TUTOR");

                    b.ToTable("TB_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Prontuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ANIMAL_ID");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<string>("CrmvSolicitanteCorrecao")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("CRMV_SOLICITANTE_CORRECAO");

                    b.Property<string>("DadosClinicos")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("DADOS_CLINICOS");

                    b.Property<DateTime?>("DataCorrecao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CORRECAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("JustificativaCorrecao")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("JUSTIFICATIVA_CORRECAO");

                    b.Property<string>("VersaoOriginalId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VERSAO_ORIGINAL_ID");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("IX_PRONTUARIO_ANIMAL");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("IX_PRONTUARIO_CONSULTA");

                    b.ToTable("TB_PRONTUARIO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.RascunhoIa", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Anamnese")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("ANAMNESE");

                    b.Property<string>("Avisos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("AVISOS");

                    b.Property<string>("Conduta")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CONDUTA");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<DateTime?>("DecididoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DECIDIDO_EM");

                    b.Property<int>("Decisao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DECISAO");

                    b.Property<int>("DuracaoMs")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACAO_MS");

                    b.Property<string>("ExameFisico")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("EXAME_FISICO");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("GERADO_EM");

                    b.Property<string>("HipotesesDiagnosticas")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("HIPOTESES_DIAGNOSTICAS");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Orientacoes")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("ORIENTACOES");

                    b.Property<bool>("Parcial")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PARCIAL");

                    b.Property<string>("SessaoCapturaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SESSAO_CAPTURA_ID");

                    b.Property<string>("TextoOrigem")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("TEXTO_ORIGEM");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique()
                        .HasDatabaseName("IX_RASCUNHO_CONSULTA");

                    b.HasIndex("SessaoCapturaId")
                        .IsUnique()
                        .HasDatabaseName("IX_RASCUNHO_SESSAO");

                    b.ToTable("TB_RASCUNHO_IA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("HASH");

                    b.Property<bool>("Revogado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("REVOGADO");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REVOGADO_EM");

                    b.Property<string>("SubstituidoPorId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SUBSTITUIDO_POR_ID");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_USUARIO");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_REFRESH_TOKEN_HASH");

                    b.HasIndex("UsuarioId", "Revogado")
                        .HasDatabaseName("IX_REFRESH_TOKEN_USUARIO");

                    b.ToTable("TB_REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.RegistroIdempotencia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CHAVE");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRA_EM");

                    b.Property<string>("Resposta")
                        .HasColumnType("CLOB")
                        .HasColumnName("RESPOSTA");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("ROTA");

                    b.Property<byte>("StatusHttp")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("STATUS_HTTP");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("IX_IDEMPOTENCIA_EXPIRACAO");

                    b.HasIndex("Chave", "UsuarioId", "Rota")
                        .IsUnique()
                        .HasDatabaseName("IX_IDEMPOTENCIA_CHAVE");

                    b.ToTable("TB_IDEMPOTENCIA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.SegmentoAudio", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CallbackTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("CALLBACK_TOKEN_HASH");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<int>("DuracaoMs")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACAO_MS");

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<int?>("FalhaMotivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FALHA_MOTIVO");

                    b.Property<int>("InicioRelativoMs")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INICIO_RELATIVO_MS");

                    b.Property<string>("MidiaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("MIDIA_ID");

                    b.Property<int>("Sequencia")
                        .HasColumnType("NUMBER(6)")
                        .HasColumnName("SEQUENCIA");

                    b.Property<string>("SessaoCapturaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SESSAO_CAPTURA_ID");

                    b.Property<byte>("Tentativas")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("TENTATIVAS");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_SEGMENTO_ESTADO");

                    b.HasIndex("SessaoCapturaId", "Sequencia")
                        .IsUnique()
                        .HasDatabaseName("IX_SEGMENTO_SESSAO_SEQUENCIA");

                    b.ToTable("TB_SEGMENTO_AUDIO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Servico", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("AceitaPlanoPet")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACEITA_PLANO_PET");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<byte>("DuracaoMinutos")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("DURACAO_MINUTOS");

                    b.Property<string>("PrestadorId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("PRESTADOR_ID");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("IX_SERVICO_PRESTADOR_TIPO");

                    b.ToTable("TB_SERVICO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.SessaoCaptura", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("CapturaAtiva")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CAPTURA_ATIVA");

                    b.Property<string>("ConsultaId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("CONSULTA_ID");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ENCERRADA_EM");

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIADA_EM");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique()
                        .HasDatabaseName("IX_SESSAO_CAPTURA_CONSULTA");

                    b.ToTable("TB_SESSAO_CAPTURA", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Slot", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FIM");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIO");

                    b.Property<DateTime?>("LockAte")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LOCK_ATE");

                    b.Property<string>("LockConsultaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("LOCK_CONSULTA_ID");

                    b.Property<string>("VeterinarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("VETERINARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "Inicio")
                        .HasDatabaseName("IX_SLOT_ESTADO_INICIO");

                    b.HasIndex("VeterinarioId", "Inicio")
                        .IsUnique()
                        .HasDatabaseName("IX_SLOT_VETERINARIO_INICIO");

                    b.ToTable("TB_SLOT", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Transcricao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<decimal?>("Confianca")
                        .HasColumnType("NUMBER(4,3)")
                        .HasColumnName("CONFIANCA");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Motor")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("MOTOR");

                    b.Property<string>("SegmentoAudioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("SEGMENTO_AUDIO_ID");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("TEXTO");

                    b.Property<string>("Trechos")
                        .HasColumnType("CLOB")
                        .HasColumnName("TRECHOS");

                    b.HasKey("Id");

                    b.HasIndex("SegmentoAudioId")
                        .IsUnique()
                        .HasDatabaseName("IX_TRANSCRICAO_SEGMENTO");

                    b.ToTable("TB_TRANSCRICAO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Tutor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<bool>("ConsentimentoAtendimento")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONSENTIMENTO_ATENDIMENTO");

                    b.Property<bool>("ConsentimentoCompartilhamento")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONSENTIMENTO_COMPARTILHAMENTO");

                    b.Property<bool>("ConsentimentoDadosAgregados")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONSENTIMENTO_DADOS_AGREGADOS");

                    b.Property<bool>("ConsentimentoLembretes")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONSENTIMENTO_LEMBRETES");

                    b.Property<bool>("ConsentimentoPromocoes")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONSENTIMENTO_PROMOCOES");

                    b.Property<DateTime?>("DataConcessaoAtendimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO_ATENDIMENTO");

                    b.Property<DateTime?>("DataConcessaoCompartilhamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO_COMPARTILHAMENTO");

                    b.Property<DateTime?>("DataConcessaoDadosAgregados")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO_DADOS_AGREGADOS");

                    b.Property<DateTime?>("DataConcessaoLembretes")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO_LEMBRETES");

                    b.Property<DateTime?>("DataConcessaoPromocoes")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONCESSAO_PROMOCOES");

                    b.Property<DateTime?>("DataConsentimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSENTIMENTO");

                    b.Property<DateTime?>("DataRevogacaoAtendimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO_ATENDIMENTO");

                    b.Property<DateTime?>("DataRevogacaoCompartilhamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO_COMPARTILHAMENTO");

                    b.Property<DateTime?>("DataRevogacaoDadosAgregados")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO_DADOS_AGREGADOS");

                    b.Property<DateTime?>("DataRevogacaoLembretes")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO_LEMBRETES");

                    b.Property<DateTime?>("DataRevogacaoPromocoes")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REVOGACAO_PROMOCOES");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("VARCHAR2(254)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TUTOR_EMAIL");

                    b.ToTable("TB_TUTOR", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Veterinario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int>("CrmvStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CRMV_STATUS");

                    b.Property<DateTime?>("CrmvValidadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRMV_VALIDADO_EM");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("VARCHAR2(254)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("ESPECIALIDADES");

                    b.Property<string>("EspeciesAtendidas")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("ESPECIES_ATENDIDAS");

                    b.Property<int>("MatchingStatus")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MATCHING_STATUS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("NotaMedia")
                        .HasColumnType("NUMBER(3,2)")
                        .HasColumnName("NOTA_MEDIA");

                    b.Property<int>("NumAvaliacoes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUM_AVALIACOES");

                    b.Property<int>("Persona")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONA");

                    b.Property<int>("Plano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANO");

                    b.Property<bool>("Publicado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PUBLICADO");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PUBLICADO_EM");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<bool>("SenhaTemporaria")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("SENHA_TEMPORARIA");

                    b.Property<string>("TitulacaoAcademica")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("TITULACAO_ACADEMICA");

                    b.Property<string>("UfAtuacao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR(2)")
                        .HasColumnName("UF_ATUACAO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_VETERINARIO_EMAIL")
                        .HasFilter("\"EMAIL\" IS NOT NULL");

                    b.HasIndex("UfAtuacao")
                        .HasDatabaseName("IX_VETERINARIO_UF");

                    b.HasIndex("Publicado", "MatchingStatus", "CrmvStatus")
                        .HasDatabaseName("IX_VETERINARIO_MATCHING");

                    b.ToTable("TB_VETERINARIO", (string)null);
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Empresa", b =>
                {
                    b.OwnsOne("Vetly.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<string>("EmpresaId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(150)")
                                .HasColumnName("BAIRRO");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(9)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(150)")
                                .HasColumnName("CIDADE");

                            b1.Property<string>("Complemento")
                                .HasColumnType("VARCHAR2(100)")
                                .HasColumnName("COMPLEMENTO");

                            b1.Property<bool>("CoordenadaRevisar")
                                .HasColumnType("NUMBER(1)")
                                .HasColumnName("COORDENADA_REVISAR");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("NUMBER(9,6)")
                                .HasColumnName("LATITUDE");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(200)")
                                .HasColumnName("LOGRADOURO");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("NUMBER(9,6)")
                                .HasColumnName("LONGITUDE");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(20)")
                                .HasColumnName("NUMERO");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("UF");

                            b1.HasKey("EmpresaId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_EMPRESA_COORDENADA");

                            b1.ToTable("TB_EMPRESA");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Vetly.Domain.Entities.Veterinario", b =>
                {
                    b.OwnsOne("Vetly.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<string>("VeterinarioId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(150)")
                                .HasColumnName("BAIRRO");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(9)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(150)")
                                .HasColumnName("CIDADE");

                            b1.Property<string>("Complemento")
                                .HasColumnType("VARCHAR2(100)")
                                .HasColumnName("COMPLEMENTO");

                            b1.Property<bool>("CoordenadaRevisar")
                                .HasColumnType("NUMBER(1)")
                                .HasColumnName("COORDENADA_REVISAR");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("NUMBER(9,6)")
                                .HasColumnName("LATITUDE");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(200)")
                                .HasColumnName("LOGRADOURO");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("NUMBER(9,6)")
                                .HasColumnName("LONGITUDE");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(20)")
                                .HasColumnName("NUMERO");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasColumnType("CHAR(2)")
                                .HasColumnName("UF");

                            b1.HasKey("VeterinarioId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_VETERINARIO_COORDENADA");

                            b1.ToTable("TB_VETERINARIO");

                            b1.WithOwner()
                                .HasForeignKey("VeterinarioId");
                        });

                    b.OwnsOne("Vetly.Domain.ValueObjects.Crmv", "Crmv", b1 =>
                        {
                            b1.Property<string>("VeterinarioId")
                                .HasColumnType("CHAR(36)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("VARCHAR2(15)")
                                .HasColumnName("CRMV");

                            b1.HasKey("VeterinarioId");

                            b1.ToTable("TB_VETERINARIO");

                            b1.WithOwner()
                                .HasForeignKey("VeterinarioId");
                        });

                    b.Navigation("Crmv")
                        .IsRequired();

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
